### ISSUE TITLE
Code doesn't compile on Mac OS 

### ISSUE THREAD

**Issue by ratsch** [ratschlab/mmr#1]
I get this error message, when I try to compile the code on Mac OS:

~/mmr > make -j 1
g++ -Wall -O9 -D_THREAD_SAFE -g -std=c++0x -pthread -o mmr mmr.cpp config.cpp Alignment.cpp BatchData.cpp OnlineData.cpp Segments.cpp Utils.cpp
mmr.cpp:379:86: warning: cast to 'void *' from smaller integer type 'unsigned int' [-Wint-to-void-pointer-cast]
                   pthread_create(&threads[tid], &attr, process_data_online_wrapper, (void *) tid); 
                                                                                     ^
1 warning generated.
Alignment.cpp:10:8: error: unknown type name 'pthread_mutex_t'; did you mean 'pthread_attr_t'?
extern pthread_mutex_t mutex_coverage;
       ^~~~~~~~~~~~~~~
       pthread_attr_t
/usr/include/sys/_pthread/_pthread_attr_t.h:30:33: note: 'pthread_attr_t' declared here
typedef __darwin_pthread_attr_t pthread_attr_t;
                                ^
...

**Comment by akahles** [comment]
MMR needs at least gcc version 4.4.7 to compile, as the native compiler in MAC OS has problems with pthread. I suggest to use macports for a newer version of gcc. To clarify this, I have added two lines to the DOCUMENTATION file.

**Comment by amckinlay** [comment]
@akahles Do you know why the native compiler has problems with Pthreads?
