### ISSUE TITLE
Error: "terminate called after throwing an instance of 'std::out_of_range'"

### ISSUE THREAD

**Issue by tdido** [ratschlab/mmr#2]
I'm getting an error when using mmr on a particular BAM file (it's worked fine with others). I'm trying to figure out the cause and would appreciate any help.

Command line I used:
`mmr -v -t 6 -b -o mmr.bam sample.bam`

Output is available in the [attached file](https://github.com/ratschlab/mmr/files/108192/mmr_output.txt).

Sample BAM file is [available here](https://tinyurl.com/mmr-error-sample).

OS is Ubuntu 12.04.5 LTS (GNU/Linux 3.2.0-75-generic x86_64)

**Comment by akahles** [comment]
Hi Tomás,
The input file needs to be sorted by read ID. The provided sample file is sorted by position.
Cheers,
Andre

**Comment by tdido** [comment]
You're right, that was the cause. Thanks.
